### ISSUE TITLE
How do I reprogram it

### ISSUE THREAD

**Issue by M-a-c-a-r-o-o-n** [CedArctic/DigiSpark-Scripts#23]
After flashing it with the window jammer is there a way to be able to flash it with a new script without it just closing IDE

**Comment by Coder427** [comment]
Plug it in when the programmer is already running.

**Comment by CedArctic** [comment]
Thanks for answering @Coder427 ! This should solve the issue. If you are still having problems post back here @M-a-c-a-r-o-o-n

**Comment by devVictorLins** [comment]
I have the same problem and I can't flash the digispark because the window closes and even with the programmer active to upload it sketch

**Comment by CedArctic** [comment]
@devVictorLins are the proper drivers installed? Also when flashing follow these steps: 
1. Hit compile and flash from arduino IDE 
2. Insert the Digispark only when you are prompted to by the command prompt, not sooner or else the digispark will start executing
