### ISSUE TITLE
rubber ducky scripts to arduino

### ISSUE THREAD

**Issue by inventorman** [CedArctic/DigiSpark-Scripts#29]
Hi and thanks for your nice project.
Could you please tell me how you converted rubber ducky scripts to Arduino code using DigiKeyboard.h library?

**Comment by CedArctic** [comment]
Sure, I wrote a converter which you can find here: https://github.com/CedArctic/digiQuack
If you have any other question feel free to re-open the issue. Good luck!

**Comment by inventorman** [comment]
> Sure, I wrote a converter which you can find here: https://github.com/CedArctic/digiQuack
> If you have any other question feel free to re-open the issue. Good luck!

Thanks, sir.
