### ISSUE TITLE
Error when i compile the Wifi profile mailer ...

### ISSUE THREAD

**Issue by zeykafx** [CedArctic/DigiSpark-Scripts#4]
I get this error :
"WiFi_Profile_Mailer:70: error: unterminated argument list invoking macro "F"
exit status 1
unterminated argument list invoking macro "F""

and the line in red is the " for(;;){ /*empty*/ }" any help ?

**Comment by zeykafx** [comment]
Hey ! I solved my problem by using a saved file aha anyway I made a base script in the arduino IDE to force change the windows language to after be able to use on an azerty machine the Digispark ! If you want I can share it but I'm fairly new to github so I don't really know how to post that ahah :)

**Comment by CedArctic** [comment]
The AZERTY modification sounds interesting, though @nassimosaz has done something similar here (https://github.com/CedArctic/DigiSpark-Scripts/tree/master/Rapid_Shell), I would love to hear what you've done and perhaps add it to the repo 👍. Thanks for taking interest in the project 😄

**Comment by CedArctic** [comment]
In the mean time I'm closing the issue as it has been resolved.
