### ISSUE TITLE
Wallpaper Changer wont hide icons

### ISSUE THREAD

**Issue by Noszeratul** [CedArctic/DigiSpark-Scripts#45]
im trying it on windows 10.....is there a Manual or Dictonary for the codes in Digi?

**Comment by CedArctic** [comment]
I'll take a look into it. Yes there are resources here:
-Digistump for the DigiSpark and their documentation: https://github.com/digistump/DigisparkArduinoIntegration/blob/master/libraries/DigisparkKeyboard/DigiKeyboard.h

-usb.org for the USB Usage IDs on page 53: http://www.usb.org/developers/hidpage/Hut1_12v2.pdf

**Comment by CedArctic** [comment]
Script executes as intended. Try modifying delays if on a slower machine
