### ISSUE TITLE
No email received

### ISSUE THREAD

**Issue by varefaz** [CedArctic/DigiSpark-Scripts#48]
Hi, I entered my username and password but I don't receive any email on the selected account. i also tried to change receiver and sender mail but nothing happens. ideas? thanks

**Comment by apsecdev** [comment]
Are you using gmail to send?  If so, ensure that the "Less Secure App Access" is enabled on the gmail account you are using to authenticate.

**Comment by Vel1khan** [comment]
> Are you using gmail to send? If so, ensure that the "Less Secure App Access" is enabled on the gmail account you are using to authenticate.

I had this issue when I first set it up and could not figure it out for the life of me. How to enable it? https://support.google.com/accounts/answer/6010255?hl=en

**Comment by CedArctic** [comment]
@apsecdev @Vel1khan thank you very much for stepping in to assist @varefaz ! Since there has been no new activity or feedback, I am marking the issue as resolved. If anything new occurs leave a comment and I will reopen it for further investigation.
