### ISSUE TITLE
Rapid Shell, decimal error

### ISSUE THREAD

**Issue by FORKY16** [CedArctic/DigiSpark-Scripts#61]
exit status 1
too many decimal points in number

getting this error while uploading code
please resolve as soon as possible

thanks

**Comment by CedArctic** [comment]
Hi,
Could you please provide more specific information to the error? Including any relevant screenshots of the error, the code you are trying to run etc.

**Comment by angelopioamirante** [comment]
> 

Did you escape the dots ??

**Comment by F0RKY0X01** [comment]
It Works, but i dropped that projects
Thank you
