### ISSUE TITLE
How to add arrow key scripts to digikeyboard.h

### ISSUE THREAD

**Issue by Chr0llo** [CedArctic/DigiSpark-Scripts#68]
I'm new to this but I can easily navigate around. Can someone please guide me adding arrow key for example KEY_ARROW_UP to digikeyboard.h file that I can't seem to find thanks in advance.

**Comment by NotRealPaz** [comment]
see usb.org's HID-usage-tables document (PDF) chapter "Keyboard/Keypad" page
0x52 arrow up
0x51 arrow down
0x4F arrow right
0x50 arrow left

**Comment by Chr0llo** [comment]
Thank you! @NotRealPaz
