### ISSUE TITLE
Script changing

### ISSUE THREAD

**Issue by StrangePigeon79** [CedArctic/DigiSpark-Scripts#75]
How can I change the script on my device?

**Comment by TheExpertNoob** [comment]
Edit it and reflash it with Arduino IDE.

**Comment by alan-insitu** [comment]
How does this work without running the existing script on the machine used to upload the new script? I guess that this is the question that the original post was asking.

**Comment by MananShah9** [comment]
Run the script from Arduino and once it says plug in device, do so... It will upload the new one and not execute the old script
